name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v3
      - run: typst compile main.typ Code-Review-Guidelines.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: Code-Review-Guidelines
          path: Code-Review-Guidelines.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} - Guidelines"
          files: Code-Review-Guidelines.pdf
